package hu.mygame.shared;

public enum State {
	BLACK_TURN, BLACK_TURN_CHESS, BLACK_WIN, DRAW, WHITE_TURN, WHITE_TURN_CHESS, WHITE_WIN, WHITE_REQUESTED_UNDO, BLACK_REQUESTED_UNDO, WHITE_REQUESTED_DRAW, BLACK_REQUESTED_DRAW
}